// Generated by scripts/build-image-registry.js. Do not edit; run `npm run images`.
import type { ImageSourcePropType } from 'react-native';

export const imageRegistry: Readonly<Record<string, ImageSourcePropType>> = {};
