// Generated by scripts/build-image-registry.js. Do not edit; run `npm run images`.
import type { ImageSourcePropType } from 'react-native';

export const imageRegistry: Readonly<Record<string, ImageSourcePropType>> = {
  "01": require("../../assets/rulers/elizabeth-i/images/01.webp"),
  "02": require("../../assets/rulers/elizabeth-i/images/02.webp"),
  "03": require("../../assets/rulers/elizabeth-i/images/03.webp"),
  "04": require("../../assets/rulers/elizabeth-i/images/04.webp"),
  "05": require("../../assets/rulers/elizabeth-i/images/05.webp"),
  "06": require("../../assets/rulers/elizabeth-i/images/06.webp"),
  "07": require("../../assets/rulers/elizabeth-i/images/07.webp"),
  "08": require("../../assets/rulers/elizabeth-i/images/08.webp"),
  "09": require("../../assets/rulers/elizabeth-i/images/09.webp"),
  "10": require("../../assets/rulers/elizabeth-i/images/10.webp"),
  "11": require("../../assets/rulers/elizabeth-i/images/11.webp"),
  "12": require("../../assets/rulers/elizabeth-i/images/12.webp"),
  "13": require("../../assets/rulers/elizabeth-i/images/13.webp"),
  "14": require("../../assets/rulers/elizabeth-i/images/14.webp"),
  "15": require("../../assets/rulers/elizabeth-i/images/15.webp"),
  "A1": require("../../assets/rulers/elizabeth-i/images/A1.webp"),
  "B1": require("../../assets/rulers/elizabeth-i/images/B1.webp"),
  "B2": require("../../assets/rulers/elizabeth-i/images/B2.webp"),
  "D1": require("../../assets/rulers/elizabeth-i/images/D1.webp"),
  "T1": require("../../assets/rulers/elizabeth-i/images/T1.webp"),
};
